baseURL = "https://vvasuki.github.io/kAvya/"
languageCode = "en-us"
title = "काव्ये विश्वासटिप्पणयः"
theme = "sanskrit-documentation-theme-hugo"
publishDir = "docs"
[params]
  githubEditMePathBase = "https://github.com/vvasuki/kAvya/edit/master/content/"
  contactLink = "https://github.com/vvasuki/kAvya/issues/new"
  env = "production"
  disqusShortcode = "vvasuki-site"